# Site settings
title: Chef Furs
description: > # this means to ignore newlines until "baseurl:"
  Chef Furs is a group of furries banding together to help improve Chef
  as a team. Here we will post news, tips, and other fun stuff.
  We own no rights to Chef and Chef is TM Chef.io
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cheffurs.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username: ChefFurs

# Build settings
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

kramdown:
  input: GFM
